// <auto-generated />
using System;
using ClubsCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClubsCore.Migrations
{
    [DbContext(typeof(ClubsContext))]
    [Migration("20210827142947_ClubsCore.Models.ClubsContextSeed")]
    partial class ClubsCoreModelsClubsContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClubsCore.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "International",
                            Type = "Other"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Math",
                            Type = "Academic"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Diving",
                            Type = "Sport"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Strollers",
                            Type = "Leisure"
                        });
                });

            modelBuilder.Entity("ClubsCore.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1999, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ali",
                            LastName = "Tayari"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1963, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dmitry",
                            LastName = "Apraksin"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2004, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ivan",
                            LastName = "Ivanou"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Petr",
                            LastName = "Petrov"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1989, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sidor",
                            LastName = "Sidorov"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2000, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pambos",
                            LastName = "Boss"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1998, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christos",
                            LastName = "Christou"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1999, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Savvas",
                            LastName = "Savvou"
                        });
                });

            modelBuilder.Entity("ClubsCore.Models.StudentClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentClubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 2,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 3,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            ClubId = 4,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 5,
                            ClubId = 3,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 6,
                            ClubId = 2,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 7,
                            ClubId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 8,
                            ClubId = 2,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 9,
                            ClubId = 3,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 10,
                            ClubId = 4,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 11,
                            ClubId = 2,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 12,
                            ClubId = 2,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 13,
                            ClubId = 1,
                            StudentId = 7
                        });
                });

            modelBuilder.Entity("ClubsCore.Models.StudentClub", b =>
                {
                    b.HasOne("ClubsCore.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubsCore.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
